### ISSUE TITLE
Fun new bookdown error!

### ISSUE THREAD

**Issue by DrMattG** [NINAnor/ecosystemCondition#108]
I have found a similar error [here](https://github.com/rstudio/bookdown/issues/15). It looks like Leaflet and Bookdown do not play nicely together. I am trying the solution (to not cache the leaflet chunks) and will let you know.... Otherwise we might need to save the leaflet maps and add them locally or just do without leaflet.

**Comment by anders-kolstad** [comment]
Is it this answer you are looking into: https://github.com/rstudio/bookdown/issues/15#issuecomment-573776659
 
And what PR is causing this?

**Comment by DrMattG** [comment]
Yes! - I am trying to render the book locally with Nature Index chapter. Not caching the chunks for that chapter does not work - I will try the other solutions (I do not fancy going the M-K route)

**Comment by DrMattG** [comment]
I have not managed to get this to work - in order to render the book I have switched to non-interactive figures. As such this issue still remains - I will create pull request of rendered book (with interactive set to FALSE) but I guess we need to find a stable solution....(I guess sorting out all the duplicate chunk names would be the solution but it sounds like a lot of work!!)

**Comment by anders-kolstad** [comment]
M-K will also cause lots of duplicated anchors (chapter names).

**Comment by anders-kolstad** [comment]
The Shiny approach would not have this issue either #20
