### ISSUE TITLE
Consider switching to QuartoBook?

### ISSUE THREAD

**Issue by DrMattG** [NINAnor/ecosystemCondition#11]
https://quarto.org/docs/books/ 
See this: https://community.rstudio.com/t/bookdown-evolution-in-response-to-quarto/133163/4 (copied below)
"Hi,

I'll try to give more insights in addition to the link you share.

As you deduced, there is a direct relationship between bookdown and Quarto book, and a rightful question about bookdown future.

One thing for sure is that both will live together and Quarto book will not replace bookdown. Quarto book is already having more features available, including all (almost) all the ones from bookdown.
Quarto Book has been developed based on the experience of bookdown but benefit of a from scratch rewrite, better integration with Pandoc features, and better project organization features. However, this does not make bookdown obselete - It brings bookdown concept and logic to other users outside of the R world, and R users can benefit from this too.
This means that we will continue development on bookdown with bug fixes and smaller enhancement from us, or from PR by the community. However, major new features will probably be only available in Quarto books (like new formats e.g HTML5 books, or specific feature e.g tufte or distill like layout).

So no, bookdown will not become irrelevant even if Quarto Book has most of the features. It is just that for new book project, we would recommend having a look at Quarto Book first as we believe the experience could be better, especially if not only R code chunks content are involved.

For those having already a book built with bookdown, we are thinking of offering some migration tools to make the switch if desired, in the aim to make that as easy as possible, with as guidance as possible. For example, when starting a new edition of the book we think this could be of interest. So yes, there will be tools to port existing bookdown project to Quarto.

But bookdown is not going away for R users and there is no incentive to change right now.

I hope this give useful addition and we are always welcoming more feedbacks and dicussions with the community, so please do not hesitate to ask and give your opinions.

Thank you !"

**Comment by anders-kolstad** [comment]
Yes!
