### ISSUE TITLE
Highlight functions that predict biomass

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/ecosystemCondition#117]
Two papers are referenced for giving global relationships for predictiog consumer biomass from consumed biomass. These could be pulled out from where they are written inside code chunks and presented also in the normal text. For prediction herbivore biomass, it is:

_NPP^0.47 * 0.643_

and for carnivores it is:

_Herbivore biomass^0.73 * 0.014_

The last relationship is not validated globally I think, and comes from African savannah studies...

**Comment by JamesDMSpeed** [comment]
Added in pull request https://github.com/NINAnor/ecosystemCondition/tree/TrophicBiomassIndicators
The carnivore relationship is indeed from African national parks, but the authors argue (and present data) that the relationship is similar for predator-prey scaling globally (including in wolf-systems - Figure 5 in Hatton et al. 2015)
