### ISSUE TITLE
echo=F in template

### ISSUE THREAD

**Issue by HannoSandvik** [NINAnor/ecosystemCondition#12]
In the Sys.Date line, the code might be made invisible using echo=F

**Comment by anders-kolstad** [comment]
Also, having Syst.date() in there make little sense since all chapers will have the same data (the reder date). We ideally want to have the date when the output files were written.

**Comment by anders-kolstad** [comment]
In the template, also change reference _state_ with reference _condition_

**Comment by anders-kolstad** [comment]
All done

**Comment by HannoSandvik** [comment]
great, thanks!
