### ISSUE TITLE
c.stars() error - don't know how to merge arrays: please specify parameter along

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/ecosystemCondition#35]
I got this error in both of the two chapters _median summer temperature_ and _climate indicators explained_. I also saw this error: _Error in combine_dimensions(dots, along_dim) : dimensions of element 1 and 2 are not identical_

I think I solved it. I relied on loading cached stars objects saved as RData. If I recreated the object to the global environment and saved as RData and read it back in, then everything was fine. But the next day it would not work again. But if I loaded yeasterdays RData file and saved as tiff and loaded the tiff file, then it would work. So my hyposthesis is that there is a kind of time stamp in the RData format causing this issue.

I think this is resolved, but I keep the issue open for a while longer in case it isn't.

**Comment by DrMattG** [comment]
Looks like this is solved - will close now
