### ISSUE TITLE
gjengroing chapter check formatting

### ISSUE THREAD

**Issue by DrMattG** [NINAnor/ecosystemCondition#63]
Hi @HannoSandvik & @zanderVenter can you have a look at the rendered version of the [gjengoring Chapter](https://ninanor.github.io/ecosystemCondition/gjengroing.html) - I need to rescale the images to fit but thought best if you check it through first and I can make all changes at the same time.

**Comment by HannoSandvik** [comment]
The rendered version looks fine. I can't find any issues beyond the enormity of some of the figures.

**Comment by zanderVenter** [comment]
Sorry for late response. Yes they are rendering well. But they are a bit large - is it possible to reduce the size a bit?

**Comment by DrMattG** [comment]
Thanks both - fixed the size issue with #70
