### ISSUE TITLE
Condition indicator or pressure indicator

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/ecosystemCondition#88]
Marianne Evju:
Hovedpoenget mitt er at slitasje og kjørespor egentlig en påvirkningsindikator. Jeg foreslår at vi snur den og bruker «Areal uten slitasje og kjørespor» som indikator for egenskapen primærproduksjon. Dette er i tråd med andre indikatorer basert på samme datasett.

**Comment by anders-kolstad** [comment]
In my mind this is relatively clear condition indicator. It reflects a more or less _lasting effect on the ecosystem_ related to a human disturbance. Removing the disturbance (trampling and off-road driving ect) will not immediately improve the indicator value, something which is a defining characteristic for a pressure indiator. The indicator further reflects an altered on-the-ground condition that can affect ecosystem properties, such as the potential for plant production. 

The solution that you suggest is to reverse the sign, or interprettative meaning, for the variable-to-indicator connection. Note that reversing the interpretation of the raw variable such that good condition reflect _high prevalence of absence of disturbance_ rather than _low prevalence of disturbance_ will not affect the scaled indicator at all. It will only change the indicator name. Perhaps for the better, but I would argue against it because the name would just get a little bit longer.

**Comment by marianneevju** [comment]
No problem with that.
